//方法的部分
let 前方法 = [
    "Many researchers have utilised 方法 to measure …",
    "One of the most well-known tools for assessing …",
    "Traditionally, 方法 has been assessed by measuring …",
    "A number of techniques have been developed to …",
    "Different methods have been proposed to classify …",
    "方法 is the main non-invasive method used to determine …",
    "Different authors have measured 方法 in a variety of ways.",
    "Several methods currently exist for the measurement of 方法.",
    "Previous studies have based their criteria for selection on …",
    "方法 is one of the most common procedures for determining …",
    "There are three main types of study design used to identify …",
    "The use of life story data has a relatively long tradition within 方法.",
    "Recent advances in 方法 methods have facilitated investigation of …",
    "There are a number of instruments available for measuring the …",
    "方法 and 同义词 are currently the most popular methods for investigating …",
    "Recently, simpler and more rapid tests of 方法 have been developed.",
    "In most recent studies, 方法 has been measured in four different ways.",
    "The use of qualitative case studies is a well-established approach in …",
    "方法s have been used in the past to investigate the mechanical properties of …",
    ]
    let 近方法 = [
    "A major advantage of 方法 is that …",
    "The benefit of this approach is that …",
    "方法 based methods provide a means of …",
    "方法 was selected for its reliability and validity.",
    "A case study approach was used to allow a …",
    "This method is particularly useful in studying …",
    "A quantitative approach was employed since …",
    "Qualitative methods offer an effective way of …",
    "The design of the researchs was based on …",
    "The 方法 method is one of the more practical ways of …",
    "The semi-structured approach was chosen because …",
    "The 方法 approach has a number of attractive features: …",
    "The advantages of 方法s are that they are simple to deliver.",
    "The second advantage of using the multivariate method is …",
    "The study uses qualitative analysis in order to gain insights into …",
    "One advantage of the 方法 analysis is that it avoids the problem of …",
    "Another advantage of using computer simulations is that it allows …",
    "Continuous sampling methods have a number of advantages over …",
    "The collaborative nature of the focus group offers another advantage …",
    "Qualitative methods can be more useful for identifying and characterising …",
    "A major problem with the experimental method is that …",
    "The main disadvantage of the experimental method is that …",
    "However, there are certain drawbacks associated with the use of …",
    "There are certain problems with the use of focus groups. One of these is that there is less …",
    ]
    let 源方法 = [
    "The solution was then assayed for 主题 using the 方法 method.",
    "方法 was prepared according to the procedure used by 作者. (时间).",
    "The analysis of 主题 was done by 方法 according to the procedure of 作者 (时间).",
    "主题 was tested with the same method that was detailed for 同义词, using 方法 …",
    "Samples were analysed for 主题 as previously reported by 作者 et al. (时间).",
    "Analysis was based on the 方法 proposed by 作者 et al. (时间).",
    "This 主题 was prepared by the procedure of 方法 used by 作者 et al. (时间) …",
    ]
    let 样本征 = [
    "The cohort was divided into two groups according to …",
    "A random sample of patients with … was recruited from …",
    "Articles were searched from January 时间 until April 时间.",
    "The sample was representative with respect to gender and …",
    "Forty-seven students studying 主题 were recruited for this study.",
    "A systematic literature review was conducted of studies that …",
    "Just over half the sample (53%) was female, of whom 69% were …",
    "Of the initial cohort of 123 students, 66 were female and 57 male.",
    "Eligible women who matched the selection criteria were identified by …",
    "Only children aged between 10 and 15 years were included in the study.",
    "The participants were divided into two groups based on their performance on …",
    "Two groups of subjects were interviewed, namely 主题 and 同义词. The first group were …",
    "The project used a convenience sample of 32 first year modern languages students.",
    "All of the participants were aged between 18 and 19 at the beginning of the study …",
    "All studies described as using some sort of 主题 procedure were included in the analysis.",
    "Participants were recruited from 15 clinics across …, covering urban and rural areas …",
    "The initial sample consisted of 200 students, 75 of whom belonged to minority groups.",
    ]
    let 样本基 = [
    "Criteria for selecting the subjects were as follows:",
    "Publications were only included in the analysis if …",
    "The participants in this study were recruited from …",
    "To identify 主题, the following parameters were used: …",
    "The area of study was chosen for its relatively small …",
    "Primary inclusion criteria for the 主题 participants were …",
    "Eligibility criteria required individuals to have received …",
    "Five individuals were excluded from the study on the basis of …",
    "A small sample was chosen because of the expected difficulty in obtaining …",
    "The subjects were selected on the basis of the degree of homogeneity of their …",
    "A comparison group of 12 male subjects without any history of 主题 was drawn from a pool of …",
    ]
    let 方法意 = [
    "In order to identify 主题 …, the participants were asked to …",
    "In order to understand how 主题 regulates 同义词, a series of transfections was performed.",
    "To establish whether …,",
    "To measure 主题, a question asking … was used.",
    "To determine whether …, the 特征 were incubated for …",
    "To rule out the possibility that 主题, the participants were …",
    "To control for bias, measurements were carried out by another person.",
    "To assess whether and how 主题s are produced and received, we measured …",
    "To see if the two methods gave the same measurement, the data was plotted and …",
    "To enable the subjects to see the computer screen clearly, the laptop was configured with …",
    "To increase the reliability of measures, each 主题 was tested twice with a 4-minute break between …",
    "To compare the scores three weeks after initial screening, a global ANOVA F-test was used",
    "The vials were capped with … to prevent …",
    "The process was repeated several times in order to remove …",
    "In an attempt to make each interviewee feel as comfortable as possible, the interviewer …",
    ]
    let 总步骤 = [
    "For the 特征 questions, a Likert scale was used.",
    "For the purpose of 特征 measurement, subjects were asked to stand …",
    "For the purpose of analysis 特征 of 主题, two segments were extracted from each …",
    "For the estimation of 特征, 主题 sample was mixed with …",
    ]
    let 被步骤 = [
    "All participants were sent …",
    "The data were normalised using …",
    "Ethical approval was obtained from …",
    "Drugs were administered by icv injection …",
    "Descriptive data were generated for all variables.",
    "The procedures of this study were approved by …",
    "Prompts were used as an aid to question two so that …",
    "Data were collected using semi-structured interviews in …",
    "Participants were thanked for their time and effort and for …",
    "The experiments were run using custom software written in …",
    "Two sets of anonymised researchs were completed by …",
    "A total of 256 samples were taken from 52 boreholes (Figure 11).",
    "The solution was washed three times with deionized water and …",
    "Significance levels were set at the 1% level using the student t-test.",
    "Data management and analysis were performed using SPSS 16.0 (2010).",
    "Published studies were identified using a search strategy developed in …",
    "Data were gathered from multiple sources at various time points during …",
    "Injection solutions were coded by a colleague to reduce experimenter bias.",
    "The pilot interviews were conducted informally by the trained interviewer …",
    "Article references were searched further for additional relevant publications …",
    ]
    let 步骤前 = [
    "To begin this process, …",
    "The first step in this process was to …",
    "The second method used to identify 主题 involved …",
    "The subjects were then shown a film individually and were asked to …",
    "The 主题 was then tested again, and this weight was recorded as …",
    "The results were corrected for the background readings and then averaged before …",
    "These ratings were then made for the ten stimuli to which the subject had been exposed …",
    "The analysis was checked when initially performed and then checked again at the end of …",
    "Finally, questions were asked as to the role of …",
    "In the follow-up phase of the study, participants were asked …",
    "The final stage of the study comprised a semi-structured interview with participants who …",
    ]
    let 步骤度 = [
    "The 特征 was then aseptically transferred to a conical flask.",
    "A sample of the concentrate was then carefully injected into …",
    "The tubes were accurately reweighed to six decimal places using …",
    "The 特征 was then placed in a 上级 tool and gradually test to …",
    "The 特征 were taken manually to allow the soil to mix well with the water.",
    "The resulting solution was gently mixed at room temperature for ten minutes and …",
    ]
    let 分析器 = [
    "Data were collected using two 方法s of 主题s.",
    "Semi-automated 方法 was carried out using 主题 software and …",
    "Using the 方法 and looking at the actual 特征, it was possible to identify that 主题 …",
    "Comparisons between the two groups of 主题 were made using unrelated t-tests.",
    "The data were recorded on 方法 recorder and transcribed using a 特征 analyser …",
    "Statistical significance was analysed using analysis of variance and t-tests as appropriate.",
    "Using an 方法, we were able to separate single 特征 into different …",
    "15 subjects of 上级 were recruited using 方法 requesting 主题 and 同义词 from …",
    "All the 方法 on the computer was carried out using Quattro Pro for Windows and …",
    ]
    let 方法缺 = [
    "In particular, the analysis of 主题 was problematic.",
    "In observational studies, there is a potential for 特征 bias from …",
    "The small size of the dataset meant that it was not possible to …",
    "Further data collection is required to determine exactly how 主题 affects 同义词.",
    "Another major source of uncertainty is in the method used to calculate 主题.",
    "In this investigation there are several sources for error. The main error is …",
    "It was not possible to investigate the significant relationships of 主题 and 同义词 further because …",
    "The responses relating to 主题 were subjective and were therefore susceptible to recall bias.",
    ]