//结果的部分
let 结目的 = [
    "The first set of questions aimed to …",
    "To compare the difference between 主题 and 同义词",
    "The purpose of Experiment was to …",
    "Simple statistical analysis was used to …",
    "The next question asked the informants …",
    "To assess 主题, the 同义词 research was used.",
    "Changes in 主题 and 同义词 were compared using …",
    "Regression analysis was used to predict the …",
    "To distinguish between these two possibilities, …",
    "The first set of analyses examined the impact of …",
    "The correlation between 主题 and 同义词 was tested using …",
    "T-tests were used to analyse the relationship between …",
    "The average scores of 主题 and 同义词 were compared in order to …",
    "In order to assess 近义词, repeated-measures ANOVAs were used.",
    "Nine items on the research measured the extent to which …",
    ]
    let 结数据 = [
    "What stands out in the table is …",
    "Closer inspection of the table shows …",
    "It is apparent from this table that very few …",
    "The most interesting aspect of this graph is …",
    "In Fig.1 there is a clear trend of decreasing …",
    "What is striking about the figures in this table is …",
    "What is interesting about the data in this table is that …",
    "The differences between 主题 and 同义词 are highlighted in Table 4.",
    "From the chart, it can be seen that by far the greatest demand is for …",
    "From this data, we can see that Study 2 resulted in the lowest value of …",
    "This table is quite revealing in several ways. First, unlike the other tables …",
    "From the data in Figure 9, it is apparent that the length of time left between …",
    "Data from this table can be compared with the data in Table 4.6 which shows …",
    "As Table III shows, there is a significant difference (t = -2.15, p = 0.03) between the two groups.",
    ]
    let 正数据 = [
    "The mean score for 主题 was …",
    "Further analysis showed that …",
    "Further statistical tests revealed …",
    "A two-way ANOVA revealed that …",
    "On average, 主题s were shown to have …",
    "Strong evidence of 主题 was found when …",
    "This result is significant at the p = 0.05 level.",
    "The results, as shown in Table 1, indicate that …",
    "A positive correlation was found between 主题 and 同义词.",
    "There was a significant positive correlation between …",
    "The difference between the 主题 and 同义词 groups was significant.",
    "There was a significant difference in 主题, t(11) = 2.906, p<0.01",
    "There was a significant difference between the two conditions …",
    "Respondents who reported low levels of 主题 also reported significantly lower levels of 同义词.",
    ]
    let 负数据 = [
    "No increase in 主题 was detected.",
    "No difference greater than 主题 was observed.",
    "No significant differences were found between …",
    "None of these differences were statistically significant.",
    "No significant difference between the two groups was evident.",
    "No significant reduction in 主题 was found compared with placebo.",
    "No evidence was found for non-linear associations between 主题 and 同义词.",
    "No significant correlation was found between 主题 scores and the 同义词 scores (p = .274)",
    "主题 appeared to be unaffected by 同义词.",
    "Only trace amounts of 主题 were detected in …",
    "There was no evidence that 主题 has an influence on …",
    "The Chi-square test did not show any significant differences between …",
    "Overall, 主题 did not affect males and females differently in these measures.",
    "A clear benefit of 主题 in the prevention of 同义词 could not be identified in this analysis.",
    "T-tests found no significant differences in mean scores on the 主题 and 同义词 subscales.",
    ]
    let 两数据 = [
    "Stimulation of 主题 cells with 同义词 did not increase the …",
    "With successive increases in intensity of the 主题, the 同义词 moved further to …",
    "Following the addition of 主题, a significant increase (P<0.05) in the 同义词 was recorded.",
    "When 主题 cells were stimulated with 同义词, no significant difference in the number of 近义词 was detected.",
    ]
    let 亮数据 = [
    "Interestingly, the 主题 was observed to …",
    "This result is somewhat counterintuitive.",
    "Interestingly, this correlation is related to …",
    "The more surprising correlation is with the …",
    "Surprisingly, only a minority of respondents …",
    "The most surprising aspect of the data is in the …",
    "The correlation between 主题 and 同义词 is interesting because …",
    "The most striking result to emerge from the data is that …",
    "Interestingly, there were also differences in the ratios of …",
    "The single most striking observation to emerge from the data comparison was …",
    ]
    let 效数据 = [
    "Although the some response to the research was poor.",
    "Thirty-two individuals returned the researchs.",
    "The response rate was 60% at six months and 56% at 12 months.",
    "Of the study population, 90 subjects completed and returned the research.",
    "Of 150 individuals who were sent invitations, 81 returned the reply slip, of whom 60 agreed to …",
    "By the end of the research period, data had been collected from 64 individuals, 23 of whom were …",
    "There were 53 responses to the question: ‘…?’",
    "Respondents were asked to indicate whether …",
    "The total number of responses for this question was …",
    "The overall response to this question was very positive.",
    "Respondents were asked to suggest other reasons for …",
    "In response to the question: ‘…?’, a range of responses was elicited.",
    "This section of the research required respondents to give information on …",
    ]
    let 比数据 = [
    "Over half of those researched reported that …",
    "A minority of participants (17%) indicated that …",
    "70% of those who were interviewed indicated that ….",
    "Almost two-thirds of the participants (64%) said that ….",
    "The majority of those who responded to this item felt that …",
    "When asked whether …, 90% of the respondents reported that …",
    "Just over half of those who answered this question reported that …",
    "In response to Question 1, most of those researched indicated that …",
    "When the participants were asked ……, the majority commented that …",
    "Of the 148 patients who completed the research, just over half indicated that …",
    ]
    let 场数据 = [
    "Another reported problem was …",
    "Opinions differed as to whether …",
    "Concerns were expressed about …",
    "A number of issues were identified …",
    "A variety of perspectives were expressed …",
    "These views surfaced mainly in relation to …",
    "Concerns regarding 主题 were more widespread.",
    "There was a sense of 主题 amongst results.",
    "Five broad themes emerged from the analysis.",
    "A common view amongst results was that …",
    "One concern expressed regarding 主题 was whether …",
    "This theme came up for example in discussions of …",
    "The themes of 主题 and 同义词 recurred throughout the dataset.",
    "Two divergent and often conflicting discourses emerged …",
    "Two discrete reasons emerged from this. First … Second …",
    "Issues related to 主题 were not particularly prominent in the interview data.",
    "A recurrent theme in the interviews was a sense amongst results that …",
    ]
    let 另数据 = [
    "It was suggested that …",
    "One result argued that …",
    "There were some suggestions that …",
    "In all cases, the informants reported that …",
    "In their accounts of the events surrounding …",
    "There were some negative comments about …",
    "The participants on the whole demonstrated …",
    "Some felt that … , while others considered that …",
    "Some results argued that … , while others …",
    "This view was echoed by another informant who ..",
    "Whilst a minority mentioned that…, all agreed that…",
    "Only a small number of respondents indicated that …",
    "A small number of those interviewed suggested that ….",
    "For a small number of participants 主题 was the reason for …",
    "The majority of participants agreed with the statement that …",
    "When asked about 主题, the participants were unanimous in the view that …",
    ]
    let 外数据 = [
    "As one result shows that ‘…’",
    "As one interviewee put it: ‘…’",
    "One informant reported that …",
    "The comment below illustrates …",
    "One participant commented: ‘ …’",
    "For example, one interviewee said: ‘…’",
    "In one case, the participant thought that …",
    "Another interviewee, when asked …, said: ‘…’",
    "Other responses to this question included: ‘…’",
    "Another interviewee alluded to the notion of …",
    "Talking about this issue an interviewee said: ‘…’",
    "Commenting on 主题, one of the interviewees said …",
    "One individual stated that ‘…’ And another commented ‘…’",
    ]
    let 结过渡 = [
    "If we now turn to …",
    "A comparison of the two results reveals …",
    "Turning now to the experimental evidence on …",
    "Comparing the two results, it can be seen that …",
    "The next section of the research was concerned with …",
    "In the final part of the research, respondents were asked …",
    ]
    let 结论点 = [
    "These results suggest that …",
    "Overall, these results indicate that …",
    "In summary, these results show that …",
    "In summary, for the informants in this study, …",
    "Together these results provide important insights into …",
    "Taken together, these results suggest that there is an association between …",
    "The results in this chapter indicate that … The next chapter, therefore, moves on to discuss the …",
    ]