//结论的部分
let 总声明 = [
    "This study set out to …",
    "This paper has argued that …",
    "This essay has discussed the reasons for …",
    "In this investigation, the aim was to assess …",
    "The aim of the present research was to examine …",
    "The purpose of the current study was to determine …",
    "The main goal of the current study was to determine …",
    "This project was undertaken to design … and evaluate …",
    "The present study was designed to determine the effect of …",
    "The second aim of this study was to investigate the effects of …",
    ]
    let 总发现 = [
    "This study has identified …",
    "This study has shown that …",
    "The research has also shown that …",
    "The second major finding was that …",
    "These experiments confirmed that …",
    "主题 made no significant difference to …",
    "This study has found that generally …",
    "The investigation of 主题 has shown that …",
    "The results of this investigation show that …",
    "主题, 同义词 and 近义词 emerged as reliable predictors of …",
    "Multiple regression analysis revealed that the …",
    "The most obvious finding to emerge from this study is that …",
    "The relevance of 主题 is clearly supported by the current findings.",
    "One of the more significant findings to emerge from this study is that …",
    ]
    let 域发现 = [
    "In general, therefore, it seems that …",
    "The results of this study indicate that …",
    "These findings suggest that in general …",
    "The findings of this study suggest that …",
    "Taken together, these results suggest that …",
    "An implication of this is the possibility that …",
    "The evidence from this study suggests that …",
    "Overall, this study strengthens the idea that …",
    "The current data highlight the importance of …",
    "The findings of this research provide insights for …",
    "The results of this research support the idea that …",
    "These data suggest that 主题 can be achieved through …",
    "The theoretical implications of these findings are unclear.",
    "The principal theoretical implication of this study is that …",
    "This study has raised important questions about the nature of …",
    "The following conclusions can be drawn from the present study …",
    "Taken together, these findings suggest a role for 主题 in promoting 同义词.",
    "The findings of this investigation complement those of earlier studies.",
    "These findings have significant implications for the understanding of how …",
    "Although this study focuses on 主题, the findings may well have a bearing on …,"
    ]
    let 总意义 = [
    "The findings will be of interest to …",
    "This thesis has provided a deeper insight into …",
    "The findings reported here shed new light on …",
    "The study contributes to our understanding of …",
    "These results add to the rapidly expanding field of …",
    "The contribution of this study has been to confirm …",
    "Before this study, evidence of 主题 was purely anecdotal.",
    "This project is the first comprehensive investigation of …",
    "The insights gained from this study may be of assistance to …",
    "This work contributes to existing knowledge of 主题 by providing …",
    "This is the largest study so far documenting a delayed onset of …",
    "Prior to this study it was difficult to make predictions about how …",
    "The analysis of 主题 undertaken here, has extended our knowledge of …",
    "The empirical findings in this study provide a new understanding of …",
    "This paper contributes to recent historiographical debates concerning …",
    "This approach will prove useful in expanding our understanding of how …",
    "This new understanding should help to improve predictions of the impact of …",
    "This is the first report on 主题 from a nationally representative cohort of patients.",
    "The methods used for this 主题 may be applied to other 主题s elsewhere in the world.",
    "The 主题 that we have identified therefore assists in our understanding of the role of …",
    "This is the first study of substantial duration which examines associations between …",
    "The findings from this study make several contributions to the current literature. First,…",
    "These findings contribute in several ways to our understanding of 主题 and provide a basis for …",
    "Recognising the limitations of the current study",
    "A limitation of this study is that …",
    "Being limited to 主题, this study lacks …",
    "The small sample size did not allow …",
    "The major limitation of this study is the …",
    "This study was limited by the absence of …",
    "主题 makes these findings less generalisable to …",
    "Thirdly, the study did not evaluate the use of …",
    "It is unfortunate that the study did not include …",
    "The scope of this study was limited in terms of …",
    "The study is limited by the lack of information on …",
    "The most important limitation lies in the fact that …",
    "The main weakness of this study was the paucity of …",
    "Since the study was limited to 主题, it was not possible to ..",
    "An additional uncontrolled factor is the possibility that …",
    "It was not possible to assess 主题; therefore, it is unknown if …",
    "An issue that was not addressed in this study was whether…",
    "The generalisability of these results is subject to certain limitations. For instance, …",
    "One source of weakness in this study which could have affected the measurements of 主题 was …",
    ]
    let 总缺陷 = [
    "Notwithstanding these limitations, the study suggests that …",
    "Whilst this study did not confirm 主题, it did partially substantiate …",
    "Despite its exploratory nature, this study offers some insight into …",
    "In spite of its limitations, the study certainly adds to our understanding of the …",
    "Notwithstanding the relatively limited sample, this work offers valuable insights into …",
    "Although the current study is based on a small sample of participants, the findings suggest …",
    ]
    let 未工作 = [
    "The question raised by this study is …",
    "The study should be repeated using …",
    "This would be a fruitful area for further work.",
    "Several questions still remain to be answered.",
    "A natural progression of this work is to analyse …",
    "More research using controlled trials is needed to …",
    "More broadly, research is also needed to determine …",
    "A further study could assess the long-term effects of …",
    "What is now needed is a cross-national study involving …",
    "Considerably more work will need to be done to determine …",
    "The precise mechanism of 主题 in insects remains to be elucidated.",
    "These findings provide the following insights for future research: …",
    "Large randomised controlled trials could provide more definitive evidence.",
    "This research has thrown up many questions in need of further investigation.",
    "A greater focus on 主题 could produce interesting findings that account more for …",
    "The issue of 主题 is an intriguing one which could be usefully explored in further research.",
    "If the debate is to be moved forward, a better understanding of 主题 needs to be developed.",
    "I suggest that before 主题 is introduced, a study similar to this one should be carried out on …",
    "More information on 主题 would help us to establish a greater degree of accuracy on this matter.",
    "Setting out recommendations for practice or policy",
    "Other types of 主题 could include: a), b). …",
    "There is, therefore, a definite need for …",
    "Greater efforts are needed to ensure …",
    "Provision of 主题 will enhance 同义词 and reduce 近义词.",
    "Another important practical implication is that …",
    "Moreover, more 主题 should be made available to …",
    "The challenge now is to fabricate 主题s that contain …",
    "Unless governments adopt 主题, 同义词 will not be attained.",
    "These findings suggest several courses of action for …",
    "A reasonable approach to tackle this issue could be to …",
    "Continued efforts are needed to make 主题 more accessible to …",
    "The findings of this study have a number of practical implications.",
    "There are a number of important changes which need to be made.",
    "Management to enhance bumble-bee populations might involve …",
    "This study suggests that 主题 should be avoided by people who are prone to …",
    "A key policy priority should therefore be to plan for the long-term care of …",
    "This information can be used to develop targetted interventions aimed at …",
    "Taken together, these findings do not support strong recommendations to …",
    "Ensuring appropriate systems, services and support for 主题 should be a priority for …",
    "The findings of this study have a number of important implications for future practice.",
    ]