//讨论的部分
let 重总证 = [
    "Several reports have shown that …",
    "As mentioned in the literature review, …",
    "Prior studies that have noted the importance of …",
    "Very little was found in the literature on the question of …",
    "Previous studies evaluating 主题 observed inconsistent results on whether …",
    "A strong relationship between 主题 and 同义词 has been reported in the literature.",
    "In reviewing the literature, no data was found on the association between 主题 and 同义词.",
    ]
    let 重目的 = [
    "The third question in this research was …",
    "An initial objective of the project was to identify …",
    "The first question in this study sought to determine …",
    "It was hypothesised that participants with a history of …",
    "The present study was designed to determine the effect of …",
    "With respect to the first research question, it was found that …",
    "This study set out with the aim of assessing the importance of 主题 in …",
    ]
    let 重结果 = [
    "One interesting finding is …",
    "The current study found that …",
    "Another important finding was that …",
    "The most interesting finding was that …",
    "In this study, 主题s were found to cause …",
    "The results of this study show/indicate that …",
    "On the question of 主题, this study found that …",
    "This experiment did not detect any evidence for …",
    "The most important clinically relevant finding was …",
    "主题 provided the largest set of significant clusters of …",
    "It is interesting to note that in all seven cases of this study …",
    "The most obvious finding to emerge from the analysis is that …",
    "In the current study, comparing 主题 with 同义词 showed that the mean degree of …",
    "The results of this study did not show that …/did not show any significant increase in …",
    ]
    let 外结果 = [
    "Surprisingly, 主题 was found to ….",
    "What is surprising is that ….",
    "One unanticipated finding was that ….",
    "Surprisingly, no differences were found in ….",
    "This finding was unexpected and suggests that ….",
    "It is somewhat surprising that no 主题 was noted in this condition ….",
    "Contrary to expectations, this study did not find a significant difference between ….",
    "However, the observed difference between 主题 and 同义词 in this study was not significant.",
    "However, the ANOVA (one way) showed that these results were not statistically significant.",
    ]
    let 重分证 = [
    "This study confirms that 主题 is associated with …",
    "This finding was also reported by 作者 et al. (时间).",
    "This finding is consistent with that of 作者 (时间) who …",
    "Comparison of the findings with those of other studies confirms …",
    "This also accords with our earlier observations, which showed that …",
    "These results reflect those of 作者 et al. (时间) who also found that …",
    "Increased activation in the 主题 in this study corroborates these earlier findings.",
    "These results corroborate the findings of a great deal of the previous work in …",
    "This finding broadly supports the work of other studies in this area linking 主题 with 同义词.",
    "In accordance with the present results, previous studies have demonstrated that …",
    "It is encouraging to compare this figure with that found by 作者 (时间) who found that …",
    "Consistent with the literature, this research found that participants who reported using 主题 also …",
    "This study supports evidence from previous observations (e.g. 作者 et al., 时间).",
    "There are similarities between the attitudes expressed by 主题 in this study and those described by …",
    ]
    let 重反证 = [
    "This study has been unable to demonstrate that …",
    "However, this result has not previously been described.",
    "This outcome is contrary to that of 作者 et al. (时间) who found …",
    "This finding is contrary to previous studies which have suggested that …",
    "In contrast to earlier findings, however, no evidence of 主题 was detected.",
    "The yields in this investigation were higher compared to those of other studies.",
    "However, the findings of the current study do not support the previous research.",
    "作者 et al. (时间) showed that … This differs from the findings presented here …",
    "The overall level was found to be 15%, lower than that of previously reported levels.",
    "It has been suggested that … (作者 et al., 时间). This does not appear to be the case.",
    "The levels observed in this investigation are far below those observed by 作者 et al. (时间).",
    "These results differ from 主题’s 时间 estimate of 同义词, but they are broadly consistent with earlier …",
    ]
    let 解释 = [
    "A possible explanation for this might be that …",
    "Another possible explanation for this is that …",
    "This result may be explained by the fact that …",
    "There are, however, other possible explanations.",
    "These relationships may partly be explained by …",
    "There are several possible explanations for this result.",
    "A possible explanation for these results may be the lack of adequate …",
    "These differences can be explained in part by the proximity of 主题 and 同义词.",
    "These factors may explain the relatively good correlation between 主题 and 同义词.",
    "This inconsistency may be due to …",
    "These results are likely to be related to …",
    "This discrepancy could be attributed to …",
    "It seems possible that these results are due to …",
    "This rather contradictory result may be due to …",
    "The observed increase in 主题 could be attributed to …",
    "It is difficult to explain this result, but it might be related to …",
    "The possible interference of 主题 cannot be ruled out.",
    "It may be that these participants benefitted from …",
    "Differences between 主题 and 同义词 may have influenced …",
    "These possible sources of error could have affected …",
    "There are two likely causes for the differences between …",
    "The reason for this is not clear but it may have something to do with …",
    "The observed correlation between 主题 and 同义词 might be explained in this way: …",
    "Since this difference has not been found elsewhere it is probably not due to …",
    ]
    let 谨慎 = [
    "Another source of uncertainty is …",
    "A note of caution is due here since …",
    "These findings may be somewhat limited by …",
    "These findings cannot be extrapolated to all patients.",
    "These data must be interpreted with caution because …",
    "It could be argued that the positive results were due to …",
    "These results therefore need to be interpreted with caution.",
    "In observational studies, there is a potential for bias from …",
    "It is important to bear in mind the possible bias in these responses.",
    "Although exclusion of 主题 did not …, these results should be interpreted with caution.",
    "However, with a small sample size, caution must be applied, as the findings might not be …",
    ]
    let 假设 = [
    "It is possible, therefore, that …",
    "It can thus be suggested that …",
    "In general, therefore, it seems that …",
    "It may be the case therefore that these variations …",
    "It is therefore likely that such connections exist between …",
    "It is possible to hypothesise that these conditions are less likely to occur in …",
    "These findings suggest that …",
    "According to these data, we can infer that …",
    "This observation may support the hypothesis that …",
    "Hence, it could conceivably be hypothesised that …",
    "The value of 主题 suggests that a weak link may exist between …",
    "These results provide further support for the hypothesis that …",
    "Therefore, 主题 could be a major factor, if not the only one, causing …",
    "Noting implications of the findings",
    "It can therefore be assumed that the …",
    "An implication of this is the possibility that …",
    "The present study raises the possibility that …",
    "One of the issues that emerges from these findings is …",
    "Some of the issues emerging from this finding relate specifically to …",
    "These findings may help us to understand …",
    "This finding, while preliminary, suggests that .…",
    "This finding has important implications for developing …",
    "This observational study suggests that a diet rich in 主题 may help prevent …",
    "These findings raise intriguing questions regarding the nature and extent of …",
    "This combination of findings provides some support for the conceptual premise that …",
    ]
    let 评论 = [
    "These findings are rather disappointing.",
    "However, these results were not very encouraging.",
    "The test was successful as it was able to identify students who …",
    "The present results are significant in at least two major respects.",
    "The results of this study do not explain the occurrence of these adverse events.",
    "These findings will doubtless be much scrutinised, but there are some immediately dependable conclusions for …",
    ]
    let 重建议 = [
    "This is an important issue for future research.",
    "Research questions that could be asked include …",
    "There are still many unanswered questions about …",
    "Several questions remain unanswered at present.",
    "Despite these promising results, questions remain.",
    "Further work is required to establish the viability of…",
    "Further research should be undertaken to investigate the …",
    "There is abundant room for further progress in determining …",
    "A further study with more focus on 主题 is therefore suggested.",
    "Future studies on the current topic are therefore recommended.",
    "To develop a full picture of 主题, additional studies will be needed that …",
    "In future investigations, it might be possible to use a different 主题 in which …",
    "Further studies, which take these variables into account, will need to be undertaken.",
    ]