//证言的部分
let 泛相关 = [
    "These literatures on 主题 have highlighted several …",
    "Different theories exist in the literature regarding 主题",
    "More recent attention has focused on the provision of …",
    "There are relatively few historical studies in the area of …",
    "A large and growing body of literature has investigated …",
    "Much of the literature since the mid-时间 emphasises the …",
    "Much of the current literature on 主题 pays particular attention to …",
    "There is a large volume of published studies describing the role of …",
    "The existing literature on 主题 is extensive and focuses particularly on …",
    "There is a relatively small body of literature that is concerned with …",
    "The generalisability of much published research on this issue is problematic.",
    "A considerable amount of literature has been published on 主题. These studies …",
    "Previous research findings into 主题 have been inconsistent and contradictory (作者, 时间; …).",
    "The academic literature on 主题 has revealed the emergence of several contrasting themes.",
    ]
    let 远相关 = [
    "Research into 主题 has a long history.",
    "For many years, this phenomenon was surprisingly neglected by …",
    "Only in the past ten years have studies of 主题 directly addressed how …",
    "Prior to the work of 作者 (时间), the role of 主题 was largely unknown.",
    "Over the past decade, most research in 主题 has emphasized the use of …",
    "In recent years, there has been an increasing amount of literature on …",
    "Early examples of research into 主题 include … (作者, 时间).",
    "During the past 30 years, much more information has become available on …",
    "The first serious discussions and analyses of 主题 emerged during the 时间 with …",
    "Over the past two decades, major advances in 上级 have allowed …",
    "Historically, research investigating the factors associated with 主题 has focused on …",
    "It is only since the work of 作者 (时间) that the study of 主题 has gained momentum.",
    "The construct of 主题 was first articulated by 作者 (时间) and popularised in his book: …",
    "Around the early 时间, small-scale research and case studies began to emerge linking …",
    "It was not until the late 时间 that historians considered 主题 worthy of scholarly attention.",
    "Awareness of 主题 is not recent, having possibly first been described in the 5th century BCE by …",
    ]
    let 域相关 = [
    "To date, several studies have investigated 主题 …",
    "A number of studies have begun to examine 主题 …",
    "Various studies have assessed the efficacy of 主题 …",
    "Researchers attempted to evaluate the impact of 主题 …",
    "A great deal of previous research into 主题 has focused on …",
    "Several studies have used longitudinal data to examine …",
    "Previous studies have explored the relationships between 主题 and 同义词.",
    "Twenty cohort study analyses have examined the relationship between …",
    "A number of authors have considered the effects of … (作者, 时间).",
    "At least 120 case-control studies worldwide have examined the relationship between 主题 and 同义词 …",
    "Numerous studies have attempted to explain … (for example, 作者, 时间).",
    ]
    let 近相关 = [
    "Several lines of evidence suggest that …",
    "Previous research has established that …",
    "Data from several studies suggest that …",
    "It is now well established from a variety of studies that …",
    "A number of studies have postulated a convergence between …",
    "Surveys such as that conducted by 作者 (时间) have shown that …",
    "Many recent studies (e.g. 作者, 时间; 作者, 时间) have shown that …",
    "Traditionally, it has been argued that … (e.g. 作者, 时间).",
    "Severalresearchers of 上级 have been published. 作者 (时间) presents …",
    "In previous studies on 主题, different variables have been found to be related to …",
    "Many historians have argued that … (e.g. 作者, 时间; Johnson, 时间; 作者, 时间).",
    "There is a consensus among social scientists that … (e.g. 作者, 时间",
    "Data from several sources have identified the increased 主题 and 同义词 associated with obesity.",
    "It has been demonstrated that a high intake of 主题 results in damage to … (作者, 时间; …).",
    "There is a large number of published studies (e.g., 作者, 时间) that describe …",
    "Some cross-sectional studies suggest an association between 主题 and 同义词 (作者, 时间).",
    "It has been suggested that levels of 主题 are independent of the size of the 同义词 (作者 et al., 时间).",
    "It has conclusively been shown that 主题 and 同义词 increase 近义词 (作者 et al., 时间).",
    ]
    let 现相关 = [
    "主题, 同义词 and 近义词 appear to be closely linked (作者, 时间).",
    "主题 appears to be positively related to both 同义词 and 近义词 (作者, 时间)",
    "主题 is a principal determining factor of 同义词 (作者, 时间; 作者, 时间).",
    "主题 is one of the most intense reactions following CHD (作者, 时间).",
    "There is an unambiguous relationship between 主题 and 同义词 (作者, 时间).",
    "主题 is significantly reduced during the first months of … (作者, 时间; 作者, 时间).",
    "主题 has been found to oppose the anti-inflammatory actions of 同义词 on 近义词 (作者, 时间).",
    "GM varieties of maize are able to cross-pollinate with non-GM varieties (作者, 时间) …",
    "A relationship exists between an individual’s working memory and their ability to … (作者, 时间).",
    ]
    let 前做法 = [
    "Most research on 主题 has been carried out in …",
    "Most researchers investigating 主题 have utilised …",
    "Using this approach, researchers have been able to …",
    "Several systematic reviews of 主题 have been undertaken.",
    "The vast majority of studies on 主题 have been quantitative.",
    "What we know about 主题 is largely based on observational studies.",
    "There are a number of large cross-sectional studies which suggest …",
    "Much of the previous research on 主题 has been exploratory in nature.",
    "Much of the 主题 research has focused on identifying and evaluating the …",
    "What we know about 主题 is largely based upon empirical studies that investigate how …",
    "Publications that concentrate on 主题 more frequently adopt a historical or chronological approach …",
    ]
    let 前人员 = [
    "作者 compared the rate of 主题 …",
    "作者 labelled these subsets as …",
    "作者 measured both components of the 主题 and 同义词 …",
    "作者 used a survey to assess the various …",
    "作者 identified that 主题 as …",
    "作者 set up a series of virtual experiments using …",
    "作者 examined the flow of international students …",
    "作者 carried out a number of investigations into the …",
    "作者 studied the effects of 主题 on unprotected nerve cells.",
    "作者 analysed the data from 72 countries and concluded that …",
    "作者 interviewed 250 undergraduate students using semi-structured …",
    "作者 performed a similar series of experiments in 时间 to show that …",
    "作者 reviewed the literature from the period and found little evidence for this …",
    "作者 conducted a series of trials in which he mixed 主题 with different quantities of …",
    "作者 investigated the differential impact of formal and non-formal education on …",
    ]
    let 前时间 = [
    "In 时间, a seminal article was published entitled …",
    "In 时间, Brown performed a bilateral ablation of the …",
    "In 时间, the publication of 主题 had a major impact on …",
    "In 时间, 作者 published his major historic survey of …",
    "In 时间, 作者 et al. published a paper in which they described …",
    "In 时间, 作者 et al. made several amino acid esters of 主题 and evaluated them as …",
    "In 时间, 作者 and co-workers demonstrated that 主题 induced in vitro resistance to …",
    "In 时间, 作者 et al. demonstrated that replacement of H2O with heavy water led to …",
    "In 时间, 作者 et al. reported a new and convenient synthetic procedure to obtain …",
    "Thirty years later, 作者 (时间) reported three cases of 主题 which …",
    "In the 时间, 作者 pointed to some of the ways in which …",
    "Following World War 1, 作者 actively searched for 主题.",
    "Almost 20 years ago, 作者 (时间) formulated his 主题 theory, centred around …",
    ]
    let 前研究 = [
    "One longitudinal study found that 主题 …",
    "A seminal study in this area is the work of 主题 …",
    "One study by 作者 (时间) examined the trend in 主题 …",
    "A recent study by 作者 and 作者 (时间) involved 主题 …",
    "A qualitative study by 作者 (时间) described how 主题 …",
    "A recent systematic literature review concluded that 主题 …",
    "Preliminary work on 主题 was undertaken by 作者 (时间).",
    "A longitudinal study of 主题 by 作者 (时间) reports that …",
    "A key study comparing 主题 and 同义词 is that of 作者 (时间), in which …",
    "The first systematic study of 主题 was reported by 作者 et al. in 时间.",
    "Detailed examination of 主题 by 作者 and 作者 (时间) showed that …",
    "Analysis of the genes involved in 主题 was first carried out by 作者 et al. (时间).",
    "A significant analysis and discussion on the subject was presented by 作者 (时间).",
    "The study of the structural behaviour of 主题 was first carried out by 作者 et al. (时间).",
    "A small scale study by 作者 (时间) reached different conclusions, finding no increase in …",
    "The study by 作者 (时间) offers probably the most comprehensive empirical analysis of …",
    "In an analysis of 主题, 作者 et al. (时间) found …",
    "In a follow-up study, 作者 et al. (时间) found that …",
    "In an investigation into 主题, 作者 et al. (时间) found …",
    "In a study investigating 主题, 作者 (时间) reported that …",
    "In a comprehensive study of 主题, 作者 (时间) found that …",
    "In a study conducted by 作者 (时间), it was shown that …",
    "In studies of rats given 主题, 作者 and colleagues found that …",
    "In a study which set out to determine 主题, 作者 (时间) found that …",
    "In a randomised controlled study of 主题, 作者 (时间) reported that …",
    "In another major study, 作者 (时间) found that just over half of the …",
    "In a recent cross-sectional study, 作者 (时间) investigated whether …",
    "In a large longitudinal study, 作者 et al. (时间) investigated the incidence of 主题 in 同义词.",
    "In one well-known recent experiment, limits on 主题 were found to be … (作者, 时间)",
    ]
    let 前话题 = [
    "To determine the effects of 主题, 作者 et al. (时间) compared …",
    "主题 was originally isolated from 同义词 in a soil sample from … (作者 et al., 时间).",
    "The electronic spectroscopy of 主题 was first studied by 作者 and 作者 in 时间.",
    "主题 formed the central focus of a study by 作者 (时间) in which the author found …",
    "To better understand the mechanisms of 主题 and its effects, 作者 (时间) analysed the …",
    "主题 was first demonstrated experimentally by 作者 (作者, 时间). In his seminal study …",
    "The 上级 relationship reaction between 主题 and 同义词 was first reported by 作者 in 时间.",
    "The way in which 主题 is regulated was studied extensively by 作者 and colleagues (作者 et al. 时间 and 时间).",
    ]
    let 前关系 = [
    "In this chapter, 作者 provides us with a number of important …",
    "In the subsequent chapter, 作者 examines the extent to which …",
    "By drawing on the concept of 主题, 作者 has been able to show that …",
    "Some analysts (e.g. 作者, 时间) have attempted to draw fine distinctions between …",
    "Drawing on an extensive range of sources, the authors set out the different ways in which …",
    "Other authors (see 作者, 时间) question the usefulness of such an approach.",
    ]
    let 前总结 = [
    "Similarly, 作者 (时间) found that 主题 …",
    "In the same vein, 作者 (时间) in his book 主题, 同义词 and 近义词 notes …",
    "This view is supported by 作者 (时间) who writes that …",
    "作者 argues that her data support 作者’s (时间) view that …",
    "作者’s (时间) work on 主题 is complemented by 作者’s (时间) study of …",
    "Almost every paper that has been written on 主题 includes a section relating to …",
    "Unlike 作者, 作者 (时间) argues that …",
    "In contrast to 作者, 作者 (时间) argues that …",
    "A broader perspective has been adopted by 作者 (时间) who argues that …",
    "Conversely, 作者 (时间) reported no significant difference in mortality between 主题 and 同义词.",
    ]